name: Build and deploy backend

on: 
  push:
    paths:
      - 'backend/'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Authenticate with GitHub package registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_ACCESS_TOKEN }}" > ~/.npmrc
    - name: yarn install and build
      run: |
        yarn install
        yarn build
      working-directory: ./backend
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr'
        options: ''
        src: './backend/'
        dest: 'web@trimmdich.f-bit.software:/var/node-apps/trimmdich'
      
    env:
      CI: true
